openapi: 3.1.0
info:
  title: Walk Bike and Transit Score
  description: This API returns the Walk Score, Transit Score, and Bike Score for any location.
  version: 1.0.0
servers:
  - url: https://api.walkscore.com
    description: Walk Score API
paths:
  /score:
    get:
      operationId: Score_get
      summary: Get Walk Score, Transit Score, and Bike Score
      parameters:
        - description: Set to 1 to request Transit Score.
          in: query
          name: transit
          schema:
            default: 1
            type: integer
        - description: Set to 1 to request Bike Score.
          in: query
          name: bike
          schema:
            default: 1
            type: integer
        - description: Return results in XML or JSON (defaults to XML).
          in: query
          name: format
          required: true
          schema:
            default: json
            type: string
        - description: The latitude of the requested location.
          in: query
          name: lat
          required: true
          schema:
            default: 47.6085
            type: number
        - description: The longitude of the requested location.
          in: query
          name: lon
          required: true
          schema:
            default: 22.3295
            type: number
        - description: The URL encoded address.
          in: query
          name: address
          required: true
          schema:
            default: 1119%208th%20Avenue%20Seattle%20WA%2098101
            type: string
        - description: Your Walk Score API Key.
          in: query
          name: wsapikey
          required: true
          schema:
            default: 61b0834f61254d3dab14e9683a592c7b
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreResponse'
        "403":
          description: Your IP address has been blocked
        "404":
          description: Invalid latitude/longitude
        "500":
          description: Walk Score API internal error
components:
  schemas:
    ScoreResponse:
      type: object
      properties:
        help_link:
          type: string
          description: Link to the help page for Walk Score, Transit Score, and Bike Score.
        logo_url:
          type: string
          description: URL of the logo for the Walk Score, Transit Score, and Bike Score.
        more_info_icon:
          type: string
          description: Icon representing more information about the scores.
        more_info_link:
          type: string
          description: Link to additional information about the Walk Score, Transit Score, and Bike Score.
        snapped_lat:
          type: number
          description: Latitude of the location to retrieve scores for.
        snapped_lon:
          type: number
          description: Longitude of the snapped point along the route, in decimal degrees.
        status:
          type: number
          description: Status code indicating the success or failure of the request.
        ws_link:
          type: string
          description: URL link to view the Walk Score of a location.
  examples:
    Score_get:
      value:
        ReqExample:
          address: 1119%208th%20Avenue%20Seattle%20WA%2098101
          bike: 1
          format: json
          lat: 47.6085
          lon: 22.3295
          transit: 1
          wsapikey: 61b0834f61254d3dab14e9683a592c7b
        RespExample:
          help_link: https://www.redfin.com/how-walk-score-works
          logo_url: https://cdn.walk.sc/images/api-logo.png
          more_info_icon: https://cdn.walk.sc/images/api-more-info.gif
          more_info_link: https://www.redfin.com/how-walk-score-works
          snapped_lat: 47.6085
          snapped_lon: 22.329
          status: 2
          ws_link: https://www.walkscore.com/score/1119-208th-20Avenue-20Seattle-20WA-2098101/lat=47.6085/lng=22.3295/?utm_source=lukesteuber.com&utm_medium=ws_api&utm_campaign=ws_api 